version: '3.8'

services:
  server:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ../backend:/app
    command: [ 'npm', 'run', 'start:dev' ]
    #    command: ['npm', 'run', 'start:debug']
    env_file:
      - ../backend/.env
